theme: jekyll-theme-slate
title: "Курс обучения программированию на Java"
baseurl: ""
about: "/Izhevsk-Java-Online-Education-Course/about"
contenturl: "/Izhevsk-Java-Online-Education-Course/content"
materialsurl: "/Izhevsk-Java-Online-Education-Course/materials/"
google_analytics: UA-144330579-1
plugins:
  - jekyll-seo-tag