theme: jekyll-theme-slate
title: "Онлайн курс обучения программированию на Java"
description: "Онлайн курс обучения программированию на Java в городе Ижевске"
baseurl: "/Izhevsk-Java-Online-Education-Course/"
contenturl: "/Izhevsk-Java-Online-Education-Course/content"
materialsurl: "/Izhevsk-Java-Online-Education-Course/materials/"
google_analytics: UA-144330579-1
plugins:
  - jekyll-seo-tag