theme: jekyll-theme-slate
title: "Курс обучения программированию на Java"
baseurl: "/course/"
about: "/course/about"
news: "/course/news"
contenturl: "/course/content"
student_rating_url: "/course/rating"
materialsurl: "/course/materials/"
badges: "/course/badges/"
google_analytics: UA-144330579-1
plugins:
  - jekyll-seo-tag