theme: jekyll-theme-slate
title: "Курс обучения программированию на Java"
baseurl: "/course/"
about: "/course/about"
contenturl: "/course/content"
materialsurl: "/course/materials/"
google_analytics: UA-144330579-1
plugins:
  - jekyll-seo-tag